services:
  mysql:
    image: mysql:9.1.0
    container_name: nextbeer-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    command: --innodb-buffer-pool-size=64M
    ports:
      - "3340:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nextbeer_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  nextbeer_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextbeer
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "80:8080"
    environment:
      PROD_DB_HOST: ${PROD_DB_HOST}
      PROD_DB_PORT: ${PROD_DB_PORT}
      PROD_DB_NAME: ${PROD_DB_NAME}
      PROD_DB_USERNAME: ${PROD_DB_USERNAME}
      PROD_DB_PASSWORD: ${PROD_DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
    volumes:
      - app-images:/app/images
    networks:
      - nextbeer_net

volumes:
  mysql-data:
  app-images:

networks:
  nextbeer_net:
    driver: bridge
